CREATE DATABASE IF NOT EXISTS kahoot_clone 
CHARACTER SET utf8mb4 
COLLATE utf8mb4_unicode_ci;

USE kahoot_clone;

CREATE TABLE Users (
    User_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Role ENUM('admin', 'player', 'host') NOT NULL DEFAULT 'player',
    Avatar VARCHAR(255),
    Email VARCHAR(255) UNIQUE NOT NULL,
    Password_Salt VARCHAR(255),
    Password_Hash VARCHAR(255),
    UserName VARCHAR(100) NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE Quizzes (
    Quiz_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Creator_ID INT UNSIGNED NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Description TEXT,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Creator_ID) REFERENCES Users(User_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Questions (
    Question_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Quiz_ID INT UNSIGNED NOT NULL,
    Question_type ENUM('MULTIPLE_CHOICE', 'OPEN_TEXT','SINGLE_CHOICE','TRUE_FALSE') NOT NULL,
    Question_text TEXT NOT NULL,
    Points INT UNSIGNED DEFAULT 100,
    Time_limit INT UNSIGNED DEFAULT 60,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Quiz_ID) REFERENCES Quizzes(Quiz_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Options (
    Option_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Question_ID INT UNSIGNED NOT NULL,
    Option_text VARCHAR(255) NOT NULL,
    Is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (Question_ID) REFERENCES Questions(Question_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Sessions (
    Session_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Quiz_ID INT UNSIGNED NOT NULL,
    Host_ID INT UNSIGNED NOT NULL,
    Game_PIN VARCHAR(20) UNIQUE NOT NULL, 
    Session_name VARCHAR(255) NOT NULL,
    Start_time DATETIME,
    End_time DATETIME,
    Is_active BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (Quiz_ID) REFERENCES Quizzes(Quiz_ID) ON DELETE CASCADE,
    FOREIGN KEY (Host_ID) REFERENCES Users(User_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Session_Players (
    Session_Player_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Session_ID INT UNSIGNED NOT NULL,
    User_ID INT UNSIGNED NOT NULL,
    Score INT NOT NULL DEFAULT 0,
    Joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Session_ID) REFERENCES Sessions(Session_ID) ON DELETE CASCADE,
    FOREIGN KEY (User_ID) REFERENCES Users(User_ID) ON DELETE CASCADE,
    UNIQUE (Session_ID, User_ID) 
) ENGINE=InnoDB;

CREATE TABLE Answers (
    Answer_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Session_ID INT UNSIGNED NOT NULL,
    User_ID INT UNSIGNED NOT NULL,
    Question_ID INT UNSIGNED NOT NULL,
    Option_ID INT UNSIGNED NULL, 
    Answer_text TEXT,            
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Session_ID) REFERENCES Sessions(Session_ID) ON DELETE CASCADE,
    FOREIGN KEY (User_ID) REFERENCES Users(User_ID) ON DELETE CASCADE,
    FOREIGN KEY (Question_ID) REFERENCES Questions(Question_ID) ON DELETE CASCADE,
    FOREIGN KEY (Option_ID) REFERENCES Options(Option_ID) ON DELETE CASCADE,
    UNIQUE (Session_ID, User_ID, Question_ID) 
) ENGINE=InnoDB;