CREATE TABLE Users (
    User_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password_Salt VARCHAR(255) NOT NULL,
    Password_Hash VARCHAR(255) NOT NULL,
    UserName VARCHAR(100) NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Quizzes (
    Quiz_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Creator_ID INT UNSIGNED NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Description TEXT,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Creator_ID) REFERENCES Users(User_ID) ON DELETE CASCADE
);

CREATE TABLE Questions (
    Question_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Quiz_ID INT UNSIGNED NOT NULL,
    Question_text TEXT NOT NULL,
    Time_limit INT UNSIGNED DEFAULT 60, -- Seconds to answer
    Points INT UNSIGNED DEFAULT 10,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Quiz_ID) REFERENCES Quizzes(Quiz_ID) ON DELETE CASCADE
);

CREATE TABLE Options (
    Option_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Question_ID INT UNSIGNED NOT NULL,
    Option_text VARCHAR(255) NOT NULL,
    Is_correct BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (Question_ID) REFERENCES Questions(Question_ID) ON DELETE CASCADE
);

CREATE TABLE Sessions (
    Session_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Quiz_ID INT UNSIGNED NOT NULL,
    Host_ID INT UNSIGNED NOT NULL,
    Game_PIN INT UNSIGNED NOT NULL UNIQUE,
    Session_name VARCHAR(255) NOT NULL,
    Start_time DATETIME,
    End_time DATETIME,
    Is_active BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (Quiz_ID) REFERENCES Quizzes(Quiz_ID) ON DELETE CASCADE,
    FOREIGN KEY (Host_ID) REFERENCES Users(User_ID) ON DELETE CASCADE
);

CREATE TABLE Session_Players (
    Session_Player_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Session_ID INT UNSIGNED NOT NULL,
    User_ID INT UNSIGNED NOT NULL,
    Score INT NOT NULL DEFAULT 0,
    Joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Session_ID) REFERENCES Sessions(Session_ID) ON DELETE CASCADE,
    FOREIGN KEY (User_ID) REFERENCES Users(User_ID) ON DELETE CASCADE,
    UNIQUE (Session_ID, User_ID)
);

CREATE TABLE Answers (
    Answer_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Session_ID INT UNSIGNED NOT NULL,
    User_ID INT UNSIGNED NOT NULL,
    Question_ID INT UNSIGNED NOT NULL,
    Option_ID INT UNSIGNED NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Session_ID) REFERENCES Sessions(Session_ID) ON DELETE CASCADE,
    FOREIGN KEY (User_ID) REFERENCES Users(User_ID) ON DELETE CASCADE,
    FOREIGN KEY (Question_ID) REFERENCES Questions(Question_ID) ON DELETE CASCADE,
    FOREIGN KEY (Option_ID) REFERENCES Options(Option_ID) ON DELETE CASCADE,
    UNIQUE (Session_ID, User_ID, Question_ID)
);
